### ISSUE TITLE
[algorithms][sorting] Selection Sort

### ISSUE THREAD

**Issue by the-cybersapien** [DSC-Chitkara/Algo-DS#1]
Implement Selection Sort in the following Languages:
- [ ] C
- [ ] C++
- [ ] Java
- [ ] Javascript
- [ ] Python
- [ ] Kotlin

_Suggest more Languages and claim that PR!_

**Comment by the-codingninja** [comment]
I will try to implement it in Javascript.
Thanks

**Comment by engrravijain** [comment]
i would like implement this in c.

**Comment by ervaibhavkumar** [comment]
I would like to implement this in C++

**Comment by AnshulJ98** [comment]
I would like to work on it in C.

**Comment by jaikathuria** [comment]
Sure @AnshulJ98! Happy Coding 👍🏻

**Comment by TanyaGoel05** [comment]
i will do in c++

**Comment by jiveshsachdeva** [comment]
I would like to do it in Java.....

**Comment by sahil261997** [comment]
i'd like implement this in c

**Comment by srishtisingla** [comment]
i want to do this in c++

**Comment by sachincool** [comment]
i want to do it in kotlin. :dancer:  :1st_place_medal:
