### ISSUE TITLE
Add some Sorting Algorithms!

### ISSUE THREAD

**Issue by the-cybersapien** [DSC-Chitkara/Algo-DS#2]
Add some sorting algorithms to the repository.
For example:
1. Bubble Sort
2. Selection Sort
3. Insertion Sort
4. Quick Sort
5. Merge Sort
6. Heap Sort

**Comment by i-Gagan** [comment]
#5

**Comment by i-Gagan** [comment]
#5 Python Bubblesort

**Comment by i-Gagan** [comment]
#5

**Comment by vaibhavsingh97** [comment]
@the-cybersapien You have to create new issues for each sort and all language as Todo. It willl help you to track and others fellow contributor too 😄

**Comment by jainkeval** [comment]
QuickSort in C & Javascript

**Comment by the-cybersapien** [comment]
@vaibhavsingh97 I agree with you. I'll create new Issues now! :smile:

**Comment by the-cybersapien** [comment]
@jainkeval Please give me 2 minutes to create new issues, and then claim them :smile:

**Comment by the-cybersapien** [comment]
Hello All,
thank you for the great response!
One of the primary reasons to create this repository is to provide those who are new to github a starting point. Contributions have been stopped for now and No PRs will be merged just yet.
