### ISSUE TITLE
Add basic Data Structures

### ISSUE THREAD

**Issue by the-cybersapien** [DSC-Chitkara/Algo-DS#3]
Add implementations for basic Data Structures such as:
- [ ] Linked List
- [ ] Circular Linked List
- [ ] Stacks
- [ ] Queues
- [ ] Trees
    - [ ] Binary Tree
    - [ ] Binary Search Tree
    - [ ] AVL Tree

Suggestions for more welcome!

**Comment by vaibhavsingh97** [comment]
@the-cybersapien can you break these issues into little ones 😄

**Comment by kcnklub** [comment]
How will the project be set up. I see that it is a empty repo now. Sorted by lang? or into Data Structures/Algorithms?

**Comment by Liamjen** [comment]
I added a simple implementation of a Single Linked List #13 

There are many missing features, but I think that there is enough done to get an idea of how a Single Linked List works, and I can add more features later if requested.

**Comment by the-cybersapien** [comment]
@vaibhavsingh97 Yes, I'd be happy to do that!

**Comment by the-cybersapien** [comment]
@kcnklub I am about to add structure to the project just now. Will be done in a moment! 
I thank you all for your contributions!

**Comment by the-cybersapien** [comment]
@Liamjen Thank you for quick contributions!
I will first add community guidelines and structuring details, Then one of my team members will review your PR! :+1:

**Comment by ArunaMaurya221B** [comment]
Can I work on the Stacks data structure  in Java?

**Comment by the-cybersapien** [comment]
Hello All,
thank you for the great response!
One of the primary reasons to create this repository is to provide those who are new to github a starting point. Contributions have been stopped for now and No PRs will be merged just yet.
